# Dataset

image_size: 32
num_classes: 10
img_channels: 1

mnist_path: "data/mnist.pkl"
fashionmnist_path: "data/fashionmnist.pkl"

image_dataset: "mnist"

# Generator

gen_base_channels: 32
bottom_width: 4
z_dim: 128
shared_dim: 8
num_chunks: 8

generator_model_file: "saved_models/generator.pth"

# Classifier

cl_base_channels: 32

classifier_model_file: "saved_models/classifier.pth"

# Training

max_epochs: 2500
max_loss: "inf"
total_tasks: 3

optimizer_lr: 0.0001
optimizer_beta_2: 0.999

features_file: "data/features.pt"

# Generator Training

gen_optimizer_beta_1: 0.0
gen_batch_size: 128
gen_max_patience: 100

images_per_task: 6000

delta: [100.0, 0.0]
alpha: [1.0, 0.0]
beta: [1.0, 0.0]
gamma: [1.0, 0.0]

# Classifier Training

cl_optimizer_beta_1: 0.5
cl_batch_size: 32
cl_max_patience: 50

truncation: 0.9

adjust_replay: [True, False]

# Validation

val_batch_size: 128

# Tasks

scenarios: {
    "scenario a": [
        {3: 1.0, 4: 1.0, 9: 1.0},
        {5: 1.0, 6: 1.0, 0: 1.0},
        {1: 1.0, 2: 1.0, 8: 1.0, 7: 1.0},
    ],
    "scenario b": [
        {3: 0.8, 4: 0.5, 9: 0.1},
        {5: 0.9, 6: 0.4, 0: 0.2},
        {1: 0.6, 2: 0.7, 8: 0.3, 7: 1.0},
    ],
    "scenario c": [
        {3: 0.3, 4: 0.2, 9: 0.6},
        {5: 0.1, 6: 0.9, 0: 0.7},
        {1: 0.8, 2: 1.0, 8: 0.4, 7: 0.5},
    ],
    "scenario d": [
        {3: 0.7, 4: 1.0, 9: 0.4},
        {5: 0.5, 6: 0.3, 0: 0.6},
        {1: 0.9, 2: 0.2, 8: 0.8, 7: 0.1},
    ],
}
