# Dataset

image_size: 32
num_classes: 10
img_channels: 1

mnist_path: "data/mnist.pkl"
fashionmnist_path: "data/fashionmnist.pkl"

image_datasets: ["mnist", "fashionmnist"]

# Generator

gen_base_channels: 32
bottom_width: 4
z_dim: 128
shared_dim: 8
num_chunks: 8

generator_model_file: "saved_models/generator.pth"

# Classifier

cl_base_channels: 32

classifier_model_file: "saved_models/classifier.pth"

# Training

max_epochs: 1000
max_loss: "inf"
total_tasks: 3

optimizer_lr: 0.0001
optimizer_beta_1: 0.5
optimizer_beta_2: 0.999

features_file: "data/features.pt"

# Generator Training

gen_batch_size: 128
gen_max_patience: 75

images_per_task: 6000
 
alpha: [1.0, 0.0]
gamma: [1.0, 0.0]
delta: 1.0
beta: 1.0

# Classifier Training

cl_batch_size: 32
cl_max_patience: 50

truncation: 0.9

adjust_replay: [True, False]

# Validation

val_batch_size: 128

# Tasks

scenarios: {
    "balanced": [
        {3: 1.0, 4: 1.0, 9: 1.0},
        {5: 1.0, 6: 1.0, 0: 1.0},
        {1: 1.0, 2: 1.0, 8: 1.0, 7: 1.0},
    ],
    "unbalanced": [
        {3: 1.0, 4: 0.6, 9: 0.3},
        {5: 0.9, 6: 0.4, 0: 0.2},
        {1: 0.5, 2: 0.7, 8: 0.1, 7: 0.8},
    ],
}
